### ISSUE TITLE
Bug : Telegram link expired 

### ISSUE THREAD

**Issue by aryasoni98** [fnplus/join-fnplus-with-a-pr#110]
<img width="244" alt="Screenshot 2021-07-01 at 3 05 28 PM" src="https://user-images.githubusercontent.com/18515597/124102212-c8d37300-da7d-11eb-9ada-e6ea5b193dff.png">

**Comment by xlogix** [comment]
Thank you for reporting this bug. I've gone ahead and updated the Telegram link. You can visit our group from there :)
