### ISSUE TITLE
Combine two members folder into one

### ISSUE THREAD

**Issue by jaiakash** [fnplus/join-fnplus-with-a-pr#115]
There are two member folder. Isnt it be better if we combine and use one folder instead of two.

**Comment by jaiakash** [comment]
My bad, there was just one user who created a different folder. 
Made the changes into final PR.

**Comment by xlogix** [comment]
Thanks! To prevent overwrites over other people's commits, I had to close your PR. Please send a new PR with your profile only and I'll be happy to add you.

**Comment by jaiakash** [comment]
ya sure
