### ISSUE TITLE
Join

### ISSUE THREAD

**Issue by estevam5s** [fnplus/join-fnplus-with-a-pr#162]
Because I want to stay on top of everything that goes on in this organization and of course, as a good dev, you have to know about the challenges of this incredible world of programming

**Comment by xlogix** [comment]
Great to hear that! Please raise an MR with your details in the /members folder.

**Comment by gitakileus** [comment]
Please invite me.
I hope I can contribute to this community.

**Comment by xlogix** [comment]
Please use this link to invite yourself! https://fnplus-inviter.herokuapp.com/

**Comment by xlogix** [comment]
Hope this helped! Closing this issue for now.
