### ISSUE TITLE
I want to join this community

### ISSUE THREAD

**Issue by ParadoxElder** [fnplus/join-fnplus-with-a-pr#163]
Hi guys!
My name is David Gavilanez - HarmonySkull
I come from Ecuador with open-source code love.
My Github link: https://github.com/HarmonySkull
I would like to join your organization to learn more and Grow.
Thank you very much!

**Comment by xlogix** [comment]
Hello!
Please send a PR with your details under the member's directory! I'll send an invitation once you do!
