### ISSUE TITLE
I would like to join this organization

### ISSUE THREAD

**Issue by HarmonySkull** [fnplus/join-fnplus-with-a-pr#164]
Hi guys!
My name is David Gavilanez - ParadoxElder
I come from Ecuador with open-source code love.
My Github link: https://github.com/ParadoxElder
I would like to join your organization to learn more and Grow.
Thank you very much!

**Comment by xlogix** [comment]
Hello!
Please send a PR with your details under the member's directory! I'll send an invitation once you do!
