### ISSUE TITLE
Request to join organization

### ISSUE THREAD

**Issue by Surajv311** [fnplus/join-fnplus-with-a-pr#65]
Can I join the organization?

**Comment by xlogix** [comment]
Yes sure. Just make sure to send a PR with your details on it. Samples are available in "members" folder

**Comment by Surajv311** [comment]
@xlogix done.

**Comment by Surajv311** [comment]
@xlogix I haven't received org. invite via mail. Could you please check?

**Comment by xlogix** [comment]
Just use this link: https://fnplus-inviter.herokuapp.com/
